version: '3.7'


services:
  #  application:
  #    image: aylien-test-joe
  #    container_name: aylien-test-joe
  #    ports:
  #      - 8080:8080
  #      - 8081:8081
  #    networks:
  #      - local

  prometheus:
    image: prom/prometheus
    container_name: prometheus
    networks:
      - local
    ports:
      - 9090:9090
    volumes:
      - ./prometheus.yaml:/etc/prometheus/prometheus.yaml

  grafana:
    depends_on:
      - prometheus
    image: grafana/grafana
    container_name: grafana
    networks:
      - local
    ports:
      - 3000:3000
